"""empty message

Revision ID: 0035f386157e
Revises: 2b82fc138279
Create Date: 2017-02-05 23:14:53.024831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0035f386157e'
down_revision = '2b82fc138279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bills', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bills', type_='foreignkey')
    op.drop_column('bills', 'owner_id')
    # ### end Alembic commands ###
