"""empty message

Revision ID: 04936db69fc1
Revises: d0caa631c733
Create Date: 2017-01-26 00:53:17.209899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04936db69fc1'
down_revision = 'd0caa631c733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
