"""empty message

Revision ID: 0799d3efed18
Revises: 931fd55e0046
Create Date: 2017-02-05 14:36:43.370030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0799d3efed18'
down_revision = '931fd55e0046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_bills',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_table('participants_bills')
    op.drop_table('participants')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('participants_id_seq'::regclass)"), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='participants_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('participants_bills',
    sa.Column('participant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bill_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name='participants_bills_bill_id_fkey'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], name='participants_bills_participant_id_fkey')
    )
    op.drop_table('users_bills')
    # ### end Alembic commands ###
