"""Add due date to bills

Revision ID: 80e2fc15678e
Revises: 31afcd344252
Create Date: 2017-03-05 20:34:55.326227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e2fc15678e'
down_revision = '31afcd344252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'due_date')
    # ### end Alembic commands ###
