"""empty message

Revision ID: 25052b33470c
Revises: e77fb81dbce6
Create Date: 2017-02-07 22:31:11.803992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25052b33470c'
down_revision = 'e77fb81dbce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminder_dates', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reminder_dates', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reminder_dates', type_='foreignkey')
    op.drop_column('reminder_dates', 'owner_id')
    # ### end Alembic commands ###
