"""empty message

Revision ID: 2b82fc138279
Revises: 47e414c88bf9
Create Date: 2017-02-05 19:07:33.735486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b82fc138279'
down_revision = '47e414c88bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'bill_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'bill_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
