"""empty message

Revision ID: 912b1182a6c2
Revises: f51cdf67ea5b
Create Date: 2017-01-25 00:10:41.612655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912b1182a6c2'
down_revision = 'f51cdf67ea5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_table('authors')
    # ### end Alembic commands ###
