"""empty message

Revision ID: cd05ce2a78a2
Revises: 0035f386157e
Create Date: 2017-02-07 00:34:14.250914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd05ce2a78a2'
down_revision = '0035f386157e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reminders', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reminders', type_='foreignkey')
    op.drop_column('reminders', 'owner_id')
    # ### end Alembic commands ###
