"""empty message

Revision ID: e77fb81dbce6
Revises: cd05ce2a78a2
Create Date: 2017-02-07 21:00:10.025114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e77fb81dbce6'
down_revision = 'cd05ce2a78a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminder_dates', sa.Column('date', sa.DateTime(), nullable=False))
    op.drop_column('reminder_dates', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminder_dates', sa.Column('data', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('reminder_dates', 'date')
    # ### end Alembic commands ###
